name: Clang tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  testing:
    name: GCC 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 15

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.28.0

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          profile_detect: 'false'

      - name: Generate Conan profile
        env:
          CXX: g++
          CC: gcc
        run: |
          conan profile detect --name=default

      - name: Check Conan profile
        run: cat ~/.conan2/profiles/default

      - name: Generate build directory
        run: mkdir -p build

      - name: Configure
        working-directory: build
        env:
          CXX: g++
          CC: gcc
        run: |
          cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build .

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure --timeout 5