name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  testing:
    name: GCC tests
    runs-on: ubuntu-latest
    container: santiagonar1/cpp-dev:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Generate build directory
        run: mkdir -p build

      - name: Configure
        working-directory: build
        env:
          CXX: g++
          CC: gcc
        run: |
          cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build .

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure --timeout 5